version: '2'
services:
  app:
    build: ./docker/
    ports:
      - "8080:80"
      - "1935:1935"
    volumes:
      -  ./docker/nginx.conf:/etc/nginx/nginx.conf
      # -  ./docker/default.conf:/etc/nginx/conf.d/default.conf
